language: python
python:
    - 3.6

services:
    - postgresql

before_script:
    - pip install -r requirements.txt
    - psql -c 'create database travis_ci_test;' -U postgres

script:
    - python manage.py test products.tests --exclude-tag=selenium