# Generated by Django 2.0.1 on 2019-10-14 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('nutrition_grade', models.CharField(blank=True, max_length=1, null=True)),
                ('nutrition_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_url', models.URLField(default='', max_length=255)),
                ('user', models.ManyToManyField(related_name='Preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('ingredients', models.TextField()),
                ('nutri_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_url', models.URLField(default='', max_length=255)),
                ('categories', models.CharField(default='', max_length=250)),
                ('is_product', models.BooleanField(default=True)),
            ],
        ),
    ]
