# Generated by Django 2.0.1 on 2019-12-02 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('ingredients', models.TextField()),
                ('nutri_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_url', models.TextField()),
                ('categories', models.CharField(default='', max_length=250)),
                ('is_product', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='preferences',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='user',
            field=models.ManyToManyField(related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
