# Generated by Django 2.0.1 on 2019-12-05 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20191204_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='user',
        ),
        migrations.AddField(
            model_name='preferences',
            name='users',
            field=models.ManyToManyField(related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
