# Generated by Django 2.0.1 on 2019-12-05 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20191205_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='users',
        ),
        migrations.AddField(
            model_name='preferences',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
